import * as path from "node:path";
import type tsLib from "typescript";
import { VueVirtualFiles } from "./vue-virtual-files.ts";

interface ParsedTsconfig {
  compilerOptions: tsLib.CompilerOptions;
  fileNames: string[];
  tsconfigDir: string;
}

export class ProgramProvider {
  /** Base programs keyed by tsconfigRootDir */
  private programs = new Map<string, tsLib.Program>();
  /** VueVirtualFiles keyed by tsconfigRootDir */
  private vueVirtualFilesMap = new Map<string, VueVirtualFiles>();
  /** Parsed tsconfig keyed by tsconfigRootDir */
  private tsconfigCache = new Map<string, ParsedTsconfig>();
  /** Per-file program cache: one entry per vueFilePath (latest code only) */
  private perFilePrograms = new Map<string, { code: string; program: tsLib.Program }>();
  /** Source file cache for CompilerHost (avoids repeated disk reads) */
  private sourceFileCache = new Map<string, tsLib.SourceFile>();
  /** Vue source file cache keyed by fileName, stores { content, sourceFile } */
  private vueSourceFileCache = new Map<string, { content: string; sourceFile: tsLib.SourceFile }>();

  private get sys(): tsLib.System {
    return this.tsModule.sys;
  }

  constructor(private tsModule: typeof tsLib) {}

  readFile(filePath: string): string | undefined {
    return this.sys.readFile(filePath, "utf-8");
  }

  getProgram(tsconfigRootDir: string): tsLib.Program {
    const cached = this.programs.get(tsconfigRootDir);
    if (cached) return cached;

    const config = this.getParsedTsconfig(tsconfigRootDir);

    const vueVirtualFiles = this.getOrCreateVueVirtualFiles(tsconfigRootDir);
    const vueFiles = this.collectVueFiles(config.fileNames, config.tsconfigDir);
    const allFileNames = [...config.fileNames, ...vueFiles];

    const host = this.createCompilerHost(config.compilerOptions, vueVirtualFiles);

    const program = this.tsModule.createProgram({
      rootNames: allFileNames,
      options: config.compilerOptions,
      host,
    });

    this.programs.set(tsconfigRootDir, program);
    return program;
  }

  /**
   * Create a program where the specified .vue file's source matches the given code
   * instead of the virtual code generated by @vue/language-core. Caches the result so that multiple parseForESLint
   * calls for the same file and code reuse the same program.
   */
  getProgramForVueCode(tsconfigRootDir: string, vueFilePath: string, code: string): tsLib.Program {
    const cached = this.perFilePrograms.get(vueFilePath);
    if (cached && cached.code === code) return cached.program;

    const baseProgram = this.getProgram(tsconfigRootDir);
    const options = baseProgram.getCompilerOptions();
    const vueVirtualFiles = this.getOrCreateVueVirtualFiles(tsconfigRootDir);
    const baseHost = this.createCompilerHost(options, vueVirtualFiles);

    // Use the previous per-file program as oldProgram if available,
    // otherwise fall back to the base program
    const oldProgram = cached?.program ?? baseProgram;

    // Determine ScriptKind from the base program's source file (set by @vue/language-core)
    const baseSf = baseProgram.getSourceFile(vueFilePath);
    const scriptKind =
      (baseSf as { scriptKind?: number })?.scriptKind ?? this.tsModule.ScriptKind.TS;

    const host: tsLib.CompilerHost = {
      ...baseHost,
      getSourceFile: (fileName, languageVersionOrOptions, onError) => {
        if (fileName === vueFilePath) {
          const languageVersion =
            typeof languageVersionOrOptions === "number"
              ? languageVersionOrOptions
              : languageVersionOrOptions.languageVersion;
          return this.tsModule.createSourceFile(fileName, code, languageVersion, true, scriptKind);
        }
        return baseHost.getSourceFile!(fileName, languageVersionOrOptions, onError);
      },
    };

    const program = this.tsModule.createProgram({
      rootNames: baseProgram.getRootFileNames(),
      options,
      host,
      oldProgram,
    });

    this.perFilePrograms.set(vueFilePath, { code, program });

    return program;
  }

  getVueVirtualFiles(): VueVirtualFiles | undefined {
    // Return the first available instance (for backward compatibility)
    for (const vf of this.vueVirtualFilesMap.values()) {
      return vf;
    }
    return undefined;
  }

  /**
   * Ensure VueVirtualFiles is initialized for the given tsconfigRootDir.
   * Used by the processor which needs virtual files before parsing begins.
   */
  getOrCreateVueVirtualFiles(tsconfigRootDir: string): VueVirtualFiles {
    const cached = this.vueVirtualFilesMap.get(tsconfigRootDir);
    if (cached) return cached;

    const config = this.getParsedTsconfig(tsconfigRootDir);
    const vueVirtualFiles = new VueVirtualFiles(this.tsModule, config.compilerOptions);
    this.vueVirtualFilesMap.set(tsconfigRootDir, vueVirtualFiles);
    return vueVirtualFiles;
  }

  reset() {
    this.programs.clear();
    this.perFilePrograms.clear();
    this.sourceFileCache.clear();
    this.vueSourceFileCache.clear();
    this.tsconfigCache.clear();
    for (const vf of this.vueVirtualFilesMap.values()) {
      vf.clearCache();
    }
    this.vueVirtualFilesMap.clear();
  }

  private getParsedTsconfig(tsconfigRootDir: string): ParsedTsconfig {
    const cached = this.tsconfigCache.get(tsconfigRootDir);
    if (cached) return cached;

    const tsconfigPath = this.findTsconfig(tsconfigRootDir);
    const configFile = this.tsModule.readConfigFile(
      tsconfigPath,
      (p: string) => this.sys.readFile(p, "utf-8") ?? "",
    );
    const tsconfigDir = path.dirname(tsconfigPath);
    const parsedConfig = this.tsModule.parseJsonConfigFileContent(
      configFile.config,
      this.sys,
      tsconfigDir,
    );

    const result: ParsedTsconfig = {
      compilerOptions: {
        ...parsedConfig.options,
        allowNonTsExtensions: true,
      },
      fileNames: parsedConfig.fileNames,
      tsconfigDir,
    };

    this.tsconfigCache.set(tsconfigRootDir, result);
    return result;
  }

  private findTsconfig(rootDir: string): string {
    const candidates = ["tsconfig.json", "tsconfig.app.json"];
    for (const name of candidates) {
      const p = path.resolve(rootDir, name);
      if (this.sys.fileExists(p)) {
        return p;
      }
    }
    return path.resolve(rootDir, "tsconfig.json");
  }

  private collectVueFiles(tsFileNames: string[], rootDir: string): string[] {
    const dirs = new Set<string>();
    dirs.add(rootDir);
    for (const f of tsFileNames) {
      dirs.add(path.dirname(f));
    }

    const commonDirs = ["src", "components", "pages", "views", "layouts"];
    for (const d of commonDirs) {
      const dirPath = path.resolve(rootDir, d);
      if (this.sys.directoryExists(dirPath)) {
        dirs.add(dirPath);
      }
    }

    const vueFiles = new Set<string>();
    for (const dir of dirs) {
      for (const file of this.sys.readDirectory(dir, [".vue"], ["node_modules"], [])) {
        vueFiles.add(file);
      }
    }

    return [...vueFiles];
  }

  private createCompilerHost(
    options: tsLib.CompilerOptions,
    vueVirtualFiles: VueVirtualFiles,
  ): tsLib.CompilerHost {
    const defaultHost = this.tsModule.createCompilerHost(options);

    const host: tsLib.CompilerHost = {
      ...defaultHost,

      fileExists: (fileName) => {
        if (fileName.endsWith(".vue")) {
          return this.sys.fileExists(fileName);
        }
        return defaultHost.fileExists(fileName);
      },

      getSourceFile: (fileName, languageVersionOrOptions, onError) => {
        if (fileName.endsWith(".vue")) {
          return this.getVueSourceFile(fileName, languageVersionOrOptions, vueVirtualFiles);
        }

        // Cache non-.vue source files to avoid repeated disk reads
        const cached = this.sourceFileCache.get(fileName);
        if (cached) return cached;

        const sf = defaultHost.getSourceFile(fileName, languageVersionOrOptions, onError);
        if (sf) {
          this.sourceFileCache.set(fileName, sf);
        }
        return sf;
      },

      resolveModuleNames: (
        moduleNames,
        containingFile,
        _reusedNames,
        _redirectedReference,
        compilerOptions,
      ) => {
        return moduleNames.map((moduleName): tsLib.ResolvedModuleFull | undefined => {
          const result = this.tsModule.resolveModuleName(
            moduleName,
            containingFile,
            compilerOptions,
            defaultHost,
          );

          if (result.resolvedModule) {
            return result.resolvedModule;
          }

          if (moduleName.endsWith(".vue")) {
            const resolved = path.resolve(path.dirname(containingFile), moduleName);
            if (this.sys.fileExists(resolved)) {
              return {
                resolvedFileName: resolved,
                extension: ".ts" as tsLib.Extension,
                isExternalLibraryImport: false,
              };
            }
          }

          return undefined;
        });
      },
    };

    return host;
  }

  private getVueSourceFile(
    fileName: string,
    languageVersionOrOptions: tsLib.ScriptTarget | tsLib.CreateSourceFileOptions,
    vueVirtualFiles: VueVirtualFiles,
  ): tsLib.SourceFile | undefined {
    const languageVersion =
      typeof languageVersionOrOptions === "number"
        ? languageVersionOrOptions
        : languageVersionOrOptions.languageVersion;

    try {
      const content = this.sys.readFile(fileName, "utf-8");
      if (content === undefined) {
        return this.tsModule.createSourceFile(
          fileName,
          "export default {} as any;",
          languageVersion,
          true,
          this.tsModule.ScriptKind.TS,
        );
      }

      const virtualFile = vueVirtualFiles.getVirtualFile(fileName, content);

      if (!virtualFile) {
        return this.tsModule.createSourceFile(
          fileName,
          "export default {} as any;",
          languageVersion,
          true,
          this.tsModule.ScriptKind.TS,
        );
      }

      // Cache the SourceFile to avoid re-creating it when ts.createProgram
      // calls getSourceFile multiple times for the same .vue file.
      const cached = this.vueSourceFileCache.get(fileName);
      if (cached && cached.content === virtualFile.code) {
        return cached.sourceFile;
      }

      const sourceFile = this.tsModule.createSourceFile(
        fileName,
        virtualFile.code,
        languageVersion,
        true,
        virtualFile.scriptKind,
      );
      this.vueSourceFileCache.set(fileName, { content: virtualFile.code, sourceFile });
      return sourceFile;
    } catch {
      return this.tsModule.createSourceFile(
        fileName,
        "export default {} as any;",
        languageVersion,
        true,
        this.tsModule.ScriptKind.TS,
      );
    }
  }
}

const providers = new Map<string, ProgramProvider>();

export function getProgramProvider(tsModule: typeof tsLib): ProgramProvider {
  const key = "__default__";
  let provider = providers.get(key);
  if (!provider) {
    provider = new ProgramProvider(tsModule);
    providers.set(key, provider);
  }
  return provider;
}
