import type tsLib from "typescript";
import { sourceToGenerated, type VirtualFileInfo } from "./vue-virtual-files.ts";
import type { ProgramProvider } from "./program-provider.ts";

/**
 * Find the TS AST node that best spans the given range in a source file.
 * When endPosition is provided, walks up from the innermost node at startPosition
 * to find one that also covers endPosition (i.e., the full expression).
 */
function findNodeAtRange(
  tsModule: typeof tsLib,
  sourceFile: tsLib.SourceFile,
  startPosition: number,
  endPosition?: number,
): tsLib.Node | undefined {
  function visit(node: tsLib.Node): tsLib.Node | undefined {
    if (startPosition < node.getStart(sourceFile) || startPosition >= node.getEnd()) {
      return undefined;
    }
    return tsModule.forEachChild(node, visit) ?? node;
  }
  let node = visit(sourceFile);
  if (!node || endPosition === undefined) return node;

  // Walk up to find a node that spans the full expression range
  while (node && node.getEnd() < endPosition && node.parent) {
    node = node.parent;
  }
  return node;
}

export interface TemplateExpressionType {
  typeString: string;
  flags: number;
}

/**
 * Provides type information for template expressions by using the virtual
 * TypeScript code and source mappings generated by @vue/language-core.
 *
 * The base Program (with virtual code) contains type-checked template code
 * like `__VLS_ctx.count > 0` for `v-if="count > 0"`. The mappings connect
 * template source positions to positions in this generated code, allowing us to
 * look up types via the TypeScript type checker.
 */
export class TemplateTypeResolver {
  private fileContentCache = new Map<string, string>();
  private vFileInfoCache = new Map<string, VirtualFileInfo>();

  constructor(
    private tsModule: typeof tsLib,
    private provider: ProgramProvider,
    private tsconfigRootDir: string,
  ) {}

  /**
   * Get the type of a template expression at a given source offset in the .vue file.
   */
  getTypeAtSourceOffset(
    vueFilePath: string,
    sourceOffset: number,
    sourceEndOffset?: number,
  ): TemplateExpressionType | undefined {
    const cachedVFileInfo = this.vFileInfoCache.get(vueFilePath);
    if (cachedVFileInfo) {
      return this.getTypeFromVirtualFile(cachedVFileInfo, vueFilePath, sourceOffset, sourceEndOffset);
    }

    const vueVirtualFiles = this.provider.getVueVirtualFiles();
    if (!vueVirtualFiles) return undefined;

    let content = this.fileContentCache.get(vueFilePath);
    if (content === undefined) {
      content = this.provider.readFile(vueFilePath);
      if (content === undefined) return undefined;
      this.fileContentCache.set(vueFilePath, content);
    }

    const vFileInfo = vueVirtualFiles.getVirtualFile(vueFilePath, content);
    if (!vFileInfo) return undefined;

    this.vFileInfoCache.set(vueFilePath, vFileInfo);
    return this.getTypeFromVirtualFile(vFileInfo, vueFilePath, sourceOffset, sourceEndOffset);
  }

  /**
   * Get the type of a template expression using pre-loaded virtual file info.
   */
  getTypeFromVirtualFile(
    vFileInfo: VirtualFileInfo,
    vueFilePath: string,
    sourceOffset: number,
    sourceEndOffset?: number,
  ): TemplateExpressionType | undefined {
    const generatedOffset = sourceToGenerated(vFileInfo.mappings, sourceOffset);
    if (generatedOffset === undefined) return undefined;

    const generatedEndOffset =
      sourceEndOffset !== undefined
        ? sourceToGenerated(vFileInfo.mappings, sourceEndOffset - 1)
        : undefined;

    const baseProgram = this.provider.getProgram(this.tsconfigRootDir);
    const sourceFile = baseProgram.getSourceFile(vueFilePath);
    if (!sourceFile) return undefined;

    const node = findNodeAtRange(
      this.tsModule,
      sourceFile,
      generatedOffset,
      generatedEndOffset !== undefined ? generatedEndOffset + 1 : undefined,
    );
    if (!node) return undefined;

    const checker = baseProgram.getTypeChecker();
    const type = checker.getTypeAtLocation(node);

    return {
      typeString: checker.typeToString(type),
      flags: type.flags,
    };
  }
}

// Singleton storage for per-file resolver instances, accessible from rules
const resolverStore = new Map<string, TemplateTypeResolver>();

export function setTemplateTypeResolver(key: string, resolver: TemplateTypeResolver): void {
  resolverStore.set(key, resolver);
}

export function getTemplateTypeResolver(key: string): TemplateTypeResolver | undefined {
  return resolverStore.get(key);
}
